[package]
name = "lemon/nen-saga-recode"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
cmdr = "evaera/cmdr@1.12.0"
table-util = "sleitnick/table-util@1.2.1"